version: "3"
services:
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    networks:
      - my-network
    volumes:
      - .\redis\redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  zookeeper:
    container_name: zookeeper
    image: zookeeper
    ports:
      - "2181:2181"
    restart: always
    networks:
      - my-network

  node-server:
    container_name: node-server
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - /server/node_modules
      - ./server:/app
    ports:
      - "8081:8081"
    networks:
      - my-network
    restart: always

  nginx:
    container_name: nginx
    image: nginx
    depends_on:
      - node-server
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "4000:80"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
